/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by DCIF CodeGen Version: R2_v2.1.0
* generated on: Wed Oct 30 12:44:55 IST 2019
*/
/**
 * description: This is a Common API DBUS diagnostics interface of audio presentation
 *   controller for Orinoco 2.0
 * author: AYatheesh
 */
#ifndef V1_COM_HARMAN_AUDIO_AUDIOPRESCTRL_audio_Pres_Ctrl_Diag_PROXY_BASE_HPP_
#define V1_COM_HARMAN_AUDIO_AUDIOPRESCTRL_audio_Pres_Ctrl_Diag_PROXY_BASE_HPP_

#include <v1/com/harman/audio/audioPresCtrl/audioPresCtrlDiag.hpp>


#include <v3/com/harman/audio/audioPresCtrl/audioPresCtrlTypes.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Attribute.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace com {
namespace harman {
namespace audio {
namespace audioPresCtrl {

class audioPresCtrlDiagProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::ObservableReadonlyAttribute<double> ActiveFrequencyAttribute;
    typedef CommonAPI::ObservableReadonlyAttribute<uint16_t> ActiveSpeakerMaskAttribute;
    typedef CommonAPI::ObservableReadonlyAttribute<uint16_t> ActiveVolumePercentAttribute;

    typedef std::function<void(const CommonAPI::CallStatus&, const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors&)> TestSpeakerAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors&)> PlaySineToneAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors&)> StopSineToneAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors&)> DiagTestStartAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors&)> DiagTestStopAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors&)> SetVolumePercentageAsyncCallback;

    /**
     * description: Attribute holding Frequency Value
     */
    virtual ActiveFrequencyAttribute& getActiveFrequencyAttribute() = 0;
    /**
     * description: Attribute holding Speaker Mask Set
     */
    virtual ActiveSpeakerMaskAttribute& getActiveSpeakerMaskAttribute() = 0;
    /**
     * description: Attribute holding Volume Set in Percentage
     */
    virtual ActiveVolumePercentAttribute& getActiveVolumePercentAttribute() = 0;


    /**
     * description: For diagnostic purpose to test one or multiple speakers 	(at)return
     *   eAudioPresErrors
     */
    virtual void TestSpeaker(const uint16_t &_speakerMask, const double &_frequency, CommonAPI::CallStatus &_internalCallStatus, ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors &_error, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> TestSpeakerAsync(const uint16_t &_speakerMask, const double &_frequency, TestSpeakerAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: This function is used to play a sine signal with sine generator with special
     *   parameters.     (at)return eAudioPresErrors
     */
    virtual void playSineTone(const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eSampleRateType &_sampleRate, const int16_t &_frequency, const int16_t &_pauseTime, const int16_t &_pulseTime, const int16_t &_repeatCount, CommonAPI::CallStatus &_internalCallStatus, ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors &_error, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> playSineToneAsync(const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eSampleRateType &_sampleRate, const int16_t &_frequency, const int16_t &_pauseTime, const int16_t &_pulseTime, const int16_t &_repeatCount, PlaySineToneAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: This function is used to stop playing sine tone for diagnostics purpose    
     *   (at)return eAudioPresErrors
     */
    virtual void StopSineTone(CommonAPI::CallStatus &_internalCallStatus, ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors &_error, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> StopSineToneAsync(StopSineToneAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: For diagnostic purpose to Start Diagnostic Session 	(at)return eAudioPresErrors
     */
    virtual void DiagTestStart(const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eDiagModeType &_diagModeType, CommonAPI::CallStatus &_internalCallStatus, ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors &_error, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> DiagTestStartAsync(const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eDiagModeType &_diagModeType, DiagTestStartAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: For diagnostic purpose to Stop Diagnostic Session 	(at)return eAudioPresErrors
     */
    virtual void DiagTestStop(const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eDiagModeType &_diagModeType, CommonAPI::CallStatus &_internalCallStatus, ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors &_error, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> DiagTestStopAsync(const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eDiagModeType &_diagModeType, DiagTestStopAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /**
     * description: For diagnostic purpose to Set Volume in percentage 	(at)return eAudioPresErrors
     */
    virtual void SetVolumePercentage(const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eDiagModeType &_diagModeType, const uint16_t &_volumePercent, CommonAPI::CallStatus &_internalCallStatus, ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eAudioPresErrors &_error, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> SetVolumePercentageAsync(const ::v3::com::harman::audio::audioPresCtrl::audioPresCtrlTypes::eDiagModeType &_diagModeType, const uint16_t &_volumePercent, SetVolumePercentageAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
};

} // namespace audioPresCtrl
} // namespace audio
} // namespace harman
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_HARMAN_AUDIO_AUDIOPRESCTRL_audio_Pres_Ctrl_Diag_PROXY_BASE_HPP_
