/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by DCIF CodeGen Version: R2_v2.1.0
* generated on: Wed Oct 30 12:44:55 IST 2019
*/
/**
 * description: "Control" interface of the NodeStateManager. 		This interface contains
 *   functions, which have direct influence on the system state and therefore have
 *   to be handled with care. The interface can only be used by certain clients,
 *   which need to be configured in the D-Bus configuration.
 */
#ifndef V2_ORG_GENIVI_NODESTATEMANAGER_LIFECYCLE_CONTROL_HPP_
#define V2_ORG_GENIVI_NODESTATEMANAGER_LIFECYCLE_CONTROL_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Types.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v2 {
namespace org {
namespace genivi {
namespace NodeStateManager {

class LifecycleControl {
public:
    virtual ~LifecycleControl() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* LifecycleControl::getInterface() {
    return ("org.genivi.NodeStateManager.LifecycleControl");
}

CommonAPI::Version LifecycleControl::getInterfaceVersion() {
    return CommonAPI::Version(2, 0);
}


} // namespace NodeStateManager
} // namespace genivi
} // namespace org
} // namespace v2

namespace CommonAPI {
}


// Compatibility
namespace v2_0 = v2;

#endif // V2_ORG_GENIVI_NODESTATEMANAGER_LIFECYCLE_CONTROL_HPP_
