/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.5.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by DCIF CodeGen Version: R2_v2.1.0
* generated on: Wed Oct 30 12:44:55 IST 2019
*/
#ifndef V1_COM_HARMAN_DCIF_RCA_Service_Types_HPP_
#define V1_COM_HARMAN_DCIF_RCA_Service_Types_HPP_



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace com {
namespace harman {
namespace dcif {

struct RCAServiceTypes {
    
    struct eActionInitiated : CommonAPI::Enumeration<int32_t> {
        enum Literal : int32_t {
            NO_ACTION = -1,
            BASS_UPDATED = 0,
            MIDDLE_UPDATED = 1,
            TREBLE_UPDATED = 2,
            PRESET_UPDATED = 3,
            BALANCEFADER_UPDATED = 4,
            VIDEO_PLAYED = 5,
            PICTURE_SELECTED = 6,
            AUXGAIN_UPDATED = 7
        };
        
        eActionInitiated() 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(Literal::NO_ACTION)) {}
        eActionInitiated(Literal _literal) 
            : CommonAPI::Enumeration<int32_t>(static_cast<int32_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast<int32_t>(Literal::NO_ACTION):
                case static_cast<int32_t>(Literal::BASS_UPDATED):
                case static_cast<int32_t>(Literal::MIDDLE_UPDATED):
                case static_cast<int32_t>(Literal::TREBLE_UPDATED):
                case static_cast<int32_t>(Literal::PRESET_UPDATED):
                case static_cast<int32_t>(Literal::BALANCEFADER_UPDATED):
                case static_cast<int32_t>(Literal::VIDEO_PLAYED):
                case static_cast<int32_t>(Literal::PICTURE_SELECTED):
                case static_cast<int32_t>(Literal::AUXGAIN_UPDATED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const eActionInitiated &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const eActionInitiated &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const eActionInitiated &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const eActionInitiated &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const eActionInitiated &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const eActionInitiated &_other) const { return (value_ > _other.value_); }
        
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast<int32_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast<int32_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast<int32_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast<int32_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast<int32_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast<int32_t>(_value)); }
    };



static inline const char* getTypeCollectionName() {
    static const char* typeCollectionName = "com.harman.dcif.RCAServiceTypes";
    return typeCollectionName;
}

inline CommonAPI::Version getTypeCollectionVersion() {
    return CommonAPI::Version(1, 0);
}

}; // struct RCAServiceTypes

} // namespace dcif
} // namespace harman
} // namespace com
} // namespace v1

namespace CommonAPI {
}


namespace std {
    //Hash for eActionInitiated
    template<>
    struct hash<::v1::com::harman::dcif::RCAServiceTypes::eActionInitiated> {
        inline size_t operator()(const ::v1::com::harman::dcif::RCAServiceTypes::eActionInitiated& eActionInitiated) const {
            return static_cast<int32_t>(eActionInitiated);
        }
    };
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_HARMAN_DCIF_RCA_Service_Types_HPP_
